kind: pipeline
name: default

steps:
- name: compilation
  image: rikorose/gcc-cmake
  commands:
  - mkdir extras/test/build
  - cd extras/test/build
  - cmake ..
  - make

- name: test
  image: rikorose/gcc-cmake
  commands:
  - cd extras/test/build
  - ./supladevicetests

- name: arduino_env
  image: rikorose/gcc-cmake
  commands:
  - wget http://downloads.arduino.cc/arduino-1.8.13-linux64.tar.xz
  - tar xf arduino-1.8.13-linux64.tar.xz
  - sudo mv arduino-1.8.13 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - ln -s $PWD /usr/local/share/arduino/libraries/Adafruit_FONA
  - arduino --install-library "Adafruit SleepyDog Library,Adafruit MQTT Library"

- name: examples_compilation
  image: rikorose/gcc-cmake
  commands:
  - arduino --verify --board arduino:avr:uno $PWD/examples/FONAtest/FONAtest.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/IncomingCall/IncomingCall.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/AdafruitIO_GPS/AdafruitIO_GPS.ino

